const objeto = ([
    
"Arroz, integral, cru",
"Arroz, tipo 1, cozido",
"Arroz, tipo 1, cru",
"Arroz, tipo 2, cozido",
"Arroz, tipo 2, cru",
"Aveia, flocos, crua",
"Biscoito, doce, maisena",
"Biscoito, doce, recheado com chocolate",
"Biscoito, doce, recheado com morango",
"Biscoito, doce, wafer, recheado de chocolate",
"Biscoito, doce, wafer, recheado de morango",
"Biscoito, salgado, cream cracker",
"Bolo, mistura para",
"Bolo, pronto, aipim",
"Bolo, pronto, chocolate",
"Bolo, pronto, coco",
"Bolo, pronto, milho",
"Canjica, branca, crua",
"Canjica, com leite integral",
"Cereais, milho, flocos, com sal",
"Cereais, milho, flocos, sem sal",
"Cereais, mingau, milho, infantil",
"Cereais, mistura para vitamina, trigo, cevada e aveia",
"Cereal matinal, milho",
"Cereal matinal, milho, a��car",
"Creme de arroz, p�",
"Creme de milho, p�",
"Curau, milho verde",
"Curau, milho verde, mistura para",
"Farinha, de arroz, enriquecida",
"Farinha, de centeio, integral",
"Farinha, de milho, amarela",
"Farinha, de rosca",
"Farinha, de trigo",
"Farinha, l�ctea, de cereais",
"Lasanha, massa fresca, cozida",
"Lasanha, massa fresca, crua",
"Macarr�o, instant�neo",
"Macarr�o, trigo, cru",
"Macarr�o, trigo, cru, com ovos",
"Milho, amido, cru",
"Milho, fub�, cru",
"Milho, verde, cru",
"Milho, verde, enlatado, drenado",
"Mingau tradicional, p�",
"Pamonha, barra para cozimento, pr�-cozida",
"P�o, aveia, forma",
"P�o, de soja",
"P�o, gl�ten, forma",
"P�o, milho, forma",
"P�o, trigo, forma, integral",
"P�o, trigo, franc�s",
"P�o, trigo, sovado",
"Pastel, de carne, cru",
"Pastel, de carne, frito",
"Pastel, de queijo, cru",
"Pastel, de queijo, frito",
"Pastel, massa, crua",
"Pastel, massa, frita",
"Pipoca, com �leo de soja, sem sal",
"Polenta, pr�-cozida",
"Torrada, p�o franc�s",
"Ab�bora, cabotian, cozida",
"Ab�bora, cabotian, crua",
"Ab�bora, menina brasileira, crua",
"Ab�bora, moranga, crua",
"Ab�bora, moranga, refogada",
"Ab�bora, pesco�o, crua",
"Abobrinha, italiana, cozida",
"Abobrinha, italiana, crua",
"Abobrinha, italiana, refogada",
"Abobrinha, paulista, crua",
"Acelga, crua",
"Agri�o, cru",
"Aipo, cru",
"Alface, americana, crua",
"Alface, crespa, crua",
"Alface, lisa, crua",
"Alface, roxa, crua",
"Alfavaca, crua",
"Alho, cru",
"Alho-por�, cru",
"Almeir�o, cru",
"Almeir�o, refogado",
"Batata, baroa, cozida",
"Batata, baroa, crua",
"Batata, doce, cozida",
"Batata, doce, crua",
"Batata, frita, tipo chips, industrializada",
"Batata, inglesa, cozida",
"Batata, inglesa, crua",
"Batata, inglesa, frita",
"Batata, inglesa, saut�",
"Berinjela, cozida",
"Berinjela, crua",
"Beterraba, cozida",
"Beterraba, crua",
"Biscoito, polvilho doce",
"Br�colis, cozido",
"Br�colis, cru",
"Car�, cozido",
"Car�, cru",
"Caruru, cru",
"Catalonha, crua",
"Catalonha, refogada",
"Cebola, crua",
"Cebolinha, crua",
"Cenoura, cozida",
"Cenoura, crua",
"Chic�ria, crua",
"Chuchu, cozido",
"Chuchu, cru",
"Coentro, folhas desidratadas",
"Couve, manteiga, crua",
"Couve, manteiga, refogada",
"Couve-flor, crua",
"Couve-flor, cozida",
"Espinafre, Nova Zel�ndia, cru",
"Espinafre, Nova Zel�ndia, refogado",
"Farinha, de mandioca, crua",
"Farinha, de mandioca, torrada",
"Farinha, de puba",
"F�cula, de mandioca",
"Feij�o, broto, cru",
"Inhame, cru",
"Jil�, cru",
"Jurubeba, crua",
"Mandioca, cozida",
"Mandioca, crua",
"Mandioca, farofa, temperada",
"Mandioca, frita",
"Manjeric�o, cru",
"Maxixe, cru",
"Mostarda, folha, crua",
"Nhoque, batata, cozido",
"Nabo, cru",
"Palmito, Ju�ara, em conserva",
"Palmito, pupunha, em conserva",
"P�o, de queijo, assado",
"P�o, de queijo, cru",
"Pepino, cru",
"Piment�o, amarelo, cru",
"Piment�o, verde, cru",
"Piment�o, vermelho, cru",
"Polvilho, doce",
"Quiabo, cru",
"Rabanete, cru",
"Repolho, branco, cru",
"Repolho, roxo, cru",
"Repolho, roxo, refogado",
"R�cula, crua",
"Salsa, crua",
"Seleta de legumes, enlatada",
"Serralha, crua",
"Taioba, crua",
"Tomate, com semente, cru",
"Tomate, extrato",
"Tomate, molho industrializado",
"Tomate, pur�",
"Tomate, salada",
"Vagem, crua",
"Abacate, cru",
"Abacaxi, cru",
"Abacaxi, polpa, congelada",
"Abiu, cru",
"A�a�, polpa, com xarope de guaran� e glucose",
"A�a�, polpa, congelada",
"Acerola, crua",
"Acerola, polpa, congelada",
"Ameixa, calda, enlatada",
"Ameixa, crua",
"Ameixa, em calda, enlatada, drenada",
"Atem�ia, crua",
"Banana, da terra, crua",
"Banana, doce em barra",
"Banana, figo, crua",
"Banana, ma��, crua",
"Banana, nanica, crua",
"Banana, ouro, crua",
"Banana, pacova, crua",
"Banana, prata, crua",
"Cacau, cru",
"Caj�-Manga, cru",
"Caj�, polpa, congelada",
"Caju, cru",
"Caju, polpa, congelada",
"Caju, suco concentrado, envasado",
"Caqui, chocolate, cru",
"Carambola, crua",
"Ciriguela, crua",
"Cupua�u, cru",
"Cupua�u, polpa, congelada",
"Figo, cru",
"Figo, enlatado, em calda",
"Fruta-p�o, crua",
"Goiaba, branca, com casca, crua",
"Goiaba, doce em pasta",
"Goiaba, doce, casc�o",
"Goiaba, vermelha, com casca, crua",
"Graviola, crua",
"Graviola, polpa, congelada",
"Jabuticaba, crua",
"Jaca, crua",
"Jambo, cru",
"Jamel�o, cru",
"Kiwi, cru",
"Laranja, ba�a, crua",
"Laranja, ba�a, suco",
"Laranja, da terra, crua",
"Laranja, da terra, suco",
"Laranja, lima, crua",
"Laranja, lima, suco",
"Laranja, p�ra, crua",
"Laranja, p�ra, suco",
"Laranja, val�ncia, crua",
"Laranja, val�ncia, suco",
"Lim�o, cravo, suco",
"Lim�o, galego, suco",
"Lim�o, tahiti, cru",
"Ma��, Argentina, com casca, crua",
"Ma��, Fuji, com casca, crua",
"Maca�ba, crua",
"Mam�o, doce em calda, drenado",
"Mam�o, Formosa, cru",
"Mam�o, Papaia, cru",
"Mam�o verde, doce em calda, drenado",
"Manga, Haden, crua",
"Manga, Palmer, crua",
"Manga, polpa, congelada",
"Manga, Tommy Atkins, crua",
"Maracuj�, cru",
"Maracuj�, polpa, congelada",
"Maracuj�, suco concentrado, envasado",
"Melancia, crua",
"Mel�o, cru",
"Mexerica, Murcote, crua",
"Mexerica, Rio, crua",
"Morango, cru",
"N�spera, crua",
"Pequi, cru",
"P�ra, Park, crua",
"P�ra, Williams, crua",
"P�ssego, Aurora, cru",
"P�ssego, enlatado, em calda",
"Pinha, crua",
"Pitanga, crua",
"Pitanga, polpa, congelada",
"Rom�, crua",
"Tamarindo, cru",
"Tangerina, Ponc�, crua",
"Tangerina, Ponc�, suco",
"Tucum�, cru",
"Umbu, cru",
"Umbu, polpa, congelada",
"Uva, It�lia, crua",
"Uva, Rubi, crua",
"Uva, suco concentrado, envasado",
"Azeite, de dend�",
"Azeite, de oliva, extra virgem",
"Manteiga, com sal",
"Manteiga, sem sal",
"Margarina, com �leo hidrogenado, com sal (65% de lip�deos)",
"Margarina, com �leo hidrogenado, sem sal (80% de lip�deos)",
"Margarina, com �leo interesterificado, com sal (65%de lip�deos)",
"Margarina, com �leo interesterificado, sem sal (65% de lip�deos)",
"�leo, de baba�u",
"�leo, de canola",
"�leo, de girassol",
"�leo, de milho",
"�leo, de pequi",
"�leo, de soja",
"Abadejo, fil�, congelado, assado",
"Abadejo, fil�, congelado,cozido",
"Abadejo, fil�, congelado, cru",
"Abadejo, fil�, congelado, grelhado",
"Atum, conserva em �leo",
"Atum, fresco, cru",
"Bacalhau, salgado, cru",
"Bacalhau, salgado, refogado",
"Ca��o, posta, com farinha de trigo, frita",
"Ca��o, posta, cozida",
"Ca��o, posta, crua",
"Camar�o, Rio Grande, grande, cozido",
"Camar�o, Rio Grande, grande, cru",
"Camar�o, Sete Barbas, sem cabe�a, com casca, frito",
"Caranguejo, cozido",
"Corimba, cru",
"Corimbat�, assado",
"Corimbat�, cozido",
"Corvina de �gua doce, crua",
"Corvina do mar, crua",
"Corvina grande, assada",
"Corvina grande, cozida",
"Dourada de �gua doce, fresca",
"Lambari, congelado, cru",
"Lambari, congelado, frito",
"Lambari, fresco,cru",
"Manjuba, com farinha de trigo, frita",
"Manjuba, frita",
"Merluza, fil�, assado",
"Merluza, fil�, cru",
"Merluza, fil�, frito",
"Pescada, branca, crua",
"Pescada, branca, frita",
"Pescada, fil�, com farinha de trigo, frito",
"Pescada, fil�, cru",
"Pescada, fil�, frito",
"Pescada, fil�, molho escabeche",
"Pescadinha, crua",
"Pintado, assado",
"Pintado, cru",
"Pintado, grelhado",
"Porquinho, cru",
"Salm�o, fil�, com pele, fresco, grelhado",
"Salm�o, sem pele, fresco, cru",
"Salm�o, sem pele, fresco, grelhado",
"Sardinha, assada",
"Sardinha, conserva em �leo",
"Sardinha, frita",
"Sardinha, inteira, crua",
"Tucunar�, fil�, congelado, cru",
"Apresuntado",
"Caldo de carne, tablete",
"Caldo de galinha, tablete",
"Carne, bovina, ac�m, mo�do, cozido",
"Carne, bovina, ac�m, mo�do, cru",
"Carne, bovina, ac�m, sem gordura, cozido",
"Carne, bovina, ac�m, sem gordura, cru",
"Carne, bovina, alm�ndegas, cruas",
"Carne, bovina, alm�ndegas, fritas",
"Carne, bovina, bucho, cozido",
"Carne, bovina, bucho, cru",
"Carne, bovina, capa de contra-fil�, com gordura, crua",
"Carne, bovina, capa de contra-fil�, com gordura, grelhada",
"Carne, bovina, capa de contra-fil�, sem gordura, crua",
"Carne, bovina, capa de contra-fil�, sem gordura, grelhada",
"Carne, bovina, charque, cozido",
"Carne, bovina, charque, cru",
"Carne, bovina, contra-fil�, � milanesa",
"Carne, bovina, contra-fil� de costela, cru",
"Carne, bovina, contra-fil� de costela, grelhado",
"Carne, bovina, contra-fil�, com gordura, cru",
"Carne, bovina, contra-fil�, com gordura, grelhado",
"Carne, bovina, contra-fil�, sem gordura, cru",
"Carne, bovina, contra-fil�, sem gordura, grelhado",
"Carne, bovina, costela, assada",
"Carne, bovina, costela, crua",
"Carne, bovina, cox�o duro, sem gordura, cozido",
"Carne, bovina, cox�o duro, sem gordura, cru",
"Carne, bovina, cox�o mole, sem gordura, cozido",
"Carne, bovina, cox�o mole, sem gordura, cru",
"Carne, bovina, cupim, assado",
"Carne, bovina, cupim, cru",
"Carne, bovina, f�gado, cru",
"Carne, bovina, f�gado, grelhado",
"Carne, bovina, fil� mingnon, sem gordura, cru",
"Carne, bovina, fil� mingnon, sem gordura, grelhado",
"Carne, bovina, flanco, sem gordura, cozido",
"Carne, bovina, flanco, sem gordura, cru",
"Carne, bovina, fraldinha, com gordura, cozida",
"Carne, bovina, fraldinha, com gordura, crua",
"Carne, bovina, lagarto, cozido",
"Carne, bovina, lagarto, cru",
"Carne, bovina, l�ngua, cozida",
"Carne, bovina, l�ngua, crua",
"Carne, bovina, maminha, crua",
"Carne, bovina, maminha, grelhada",
"Carne, bovina, miolo de alcatra, sem gordura, cru",
"Carne, bovina, miolo de alcatra, sem gordura, grelhado",
"Carne, bovina, m�sculo, sem gordura, cozido",
"Carne, bovina, m�sculo, sem gordura, cru",
"Carne, bovina, paleta, com gordura, crua",
"Carne, bovina, paleta, sem gordura, cozida",
"Carne, bovina, paleta, sem gordura, crua",
"Carne, bovina, patinho, sem gordura, cru",
"Carne, bovina, patinho, sem gordura, grelhado",
"Carne, bovina, peito, sem gordura, cozido",
"Carne, bovina, peito, sem gordura, cru",
"Carne, bovina, picanha, com gordura, crua",
"Carne, bovina, picanha, com gordura, grelhada",
"Carne, bovina, picanha, sem gordura, crua",
"Carne, bovina, picanha, sem gordura, grelhada",
"Carne, bovina, seca, cozida",
"Carne, bovina, seca, crua",
"Coxinha de frango, frita",
"Croquete, de carne, cru",
"Croquete, de carne, frito",
"Empada de frango, pr�-cozida, assada",
"Empada, de frango, pr�-cozida",
"Frango, asa, com pele, crua",
"Frango, caipira, inteiro, com pele, cozido",
"Frango, caipira, inteiro, sem pele, cozido",
"Frango, cora��o, cru",
"Frango, cora��o, grelhado",
"Frango, coxa, com pele, assada",
"Frango, coxa, com pele, crua",
"Frango, coxa, sem pele, cozida",
"Frango, coxa, sem pele, crua",
"Frango, f�gado, cru",
"Frango, fil�, � milanesa",
"Frango, inteiro, com pele, cru",
"Frango, inteiro, sem pele, assado",
"Frango, inteiro, sem pele, cozido",
"Frango, inteiro, sem pele, cru",
"Frango, peito, com pele, assado",
"Frango, peito, com pele, cru",
"Frango, peito, sem pele, cozido",
"Frango, peito, sem pele, cru",
"Frango, peito, sem pele, grelhado",
"Frango, sobrecoxa, com pele, assada",
"Frango, sobrecoxa, com pele, crua",
"Frango, sobrecoxa, sem pele, assada",
"Frango, sobrecoxa, sem pele, crua",
"Hamb�rguer, bovino, cru",
"Hamb�rguer, bovino, frito",
"Hamb�rguer, bovino, grelhado",
"Ling�i�a, frango, crua",
"Ling�i�a, frango, frita",
"Ling�i�a, frango, grelhada",
"Ling�i�a, porco, crua",
"Ling�i�a, porco, frita",
"Ling�i�a, porco, grelhada",
"Mortadela",
"Peru, congelado, assado",
"Peru, congelado, cru",
"Porco, bisteca, crua",
"Porco, bisteca, frita",
"Porco, bisteca, grelhada",
"Porco, costela, assada",
"Porco, costela, crua",
"Porco, lombo, assado",
"Porco, lombo, cru",
"Porco, orelha, salgada, crua",
"Porco, pernil, assado",
"Porco, pernil, cru",
"Porco, rabo, salgado, cru",
"Presunto, com capa de gordura",
"Presunto, sem capa de gordura",
"Quibe, assado",
"Quibe, cru",
"Quibe, frito",
"Salame",
"Toucinho, cru",
"Toucinho, frito",
"Bebida l�ctea, p�ssego",
"Creme de Leite",
"Iogurte, natural",
"Iogurte, natural, desnatado",
"Iogurte, sabor abacaxi",
"Iogurte, sabor morango",
"Iogurte, sabor p�ssego",
"Leite, condensado",
"Leite, de cabra",
"Leite, de vaca, achocolatado",
"Leite, de vaca, desnatado, p�",
"Leite, de vaca, desnatado, UHT",
"Leite, de vaca, integral",
"Leite, de vaca, integral, p�",
"Leite, fermentado",
"Queijo, minas, frescal",
"Queijo, minas, meia cura",
"Queijo, mozarela",
"Queijo, parmes�o",
"Queijo, pasteurizado",
"Queijo, petit suisse, morango",
"Queijo, prato",
"Maria mole",
"Queijo, ricota",
"Bebida isot�nica, sabores variados",
"Caf�, infus�o 10%",
"Cana, aguardente 1",
"Cana, caldo de",
"Cerveja, pilsen 2",
"Ch�, erva-doce, infus�o 5%",
"Ch�, mate, infus�o 5%",
"Ch�, preto, infus�o 5%",
"Coco, �gua de",
"Refrigerante, tipo �gua t�nica",
"Refrigerante, tipo cola",
"Refrigerante, tipo guaran�",
"Refrigerante, tipo laranja",
"Refrigerante, tipo lim�o",
"Omelete, de queijo",
"Ovo, de codorna, inteiro, cru",
"Ovo, de galinha, clara, cozida/10minutos",
"Ovo, de galinha, gema, cozida/10minutos",
"Ovo, de galinha, inteiro, cozido/10minutos",
"Ovo, de galinha, inteiro, cru",
"Ovo, de galinha, inteiro, frito",
"Achocolatado, p�",
"A��car, cristal",
"A��car, mascavo",
"A��car, refinado",
"Chocolate, ao leite",
"Chocolate, ao leite, com castanha do Par�",
"Chocolate, ao leite, diet�tico",
"Chocolate, meio amargo",
"Cocada branca",
"Doce, de ab�bora, cremoso",
"Doce, de leite, cremoso",
"Gel�ia, mocot�, natural",
"Glicose de milho",
"Maria mole",
"Maria mole, coco queimado",
"Marmelada",
"Mel, de abelha",
"Melado",
"Quindim",
"Rapadura",
"Caf�, p�, torrado",
"Capuccino, p�",
"Fermento em p�, qu�mico",
"Fermento, biol�gico, levedura, tablete",
"Gelatina, sabores variados, p�",
"Sal, diet�tico",
"Sal, grosso",
"Shoyu",
"Tempero a base de sal",
"Azeitona, preta, conserva",
"Azeitona, verde, conserva",
"Chantilly, spray, com gordura vegetal",
"Leite, de coco",
"Maionese, tradicional com ovos",
"Acaraj�",
"Arroz carreteiro",
"Bai�o de dois, arroz e feij�o-de-corda",
"Barreado",
"Bife � cavalo, com contra fil�",
"Bolinho de arroz",
"Camar�o � baiana",
"Charuto, de repolho",
"Cuscuz, de milho, cozido com sal",
"Cuscuz, paulista",
"Cux�, molho",
"Dobradinha",
"Estrogonofe de carne",
"Estrogonofe de frango",
"Feij�o tropeiro mineiro",
"Feijoada",
"Frango, com a�afr�o",
"Macarr�o, molho bolognesa",
"Mani�oba",
"Quibebe",
"Salada, de legumes, com maionese",
"Salada, de legumes, cozida no vapor",
"Salpic�o, de frango",
"Sarapatel",
"Tabule",
"Tacac�",
"Tapioca, com manteiga",
"Tucupi, com pimenta-de-cheiro",
"Vaca atolada",
"Vatap�",
"Virado � paulista",
"Yakisoba",
"Amendoim, gr�o, cru",
"Amendoim, torrado, salgado",
"Ervilha, em vagem",
"Ervilha, enlatada, drenada",
"Feij�o, carioca, cozido",
"Feij�o, carioca, cru",
"Feij�o, fradinho, cozido",
"Feij�o, fradinho, cru",
"Feij�o, jalo, cozido",
"Feij�o, jalo, cru",
"Feij�o, preto, cozido",
"Feij�o, preto, cru",
"Feij�o, rajado, cozido",
"Feij�o, rajado, cru",
"Feij�o, rosinha, cozido",
"Feij�o, rosinha, cru",
"Feij�o, roxo, cozido",
"Feij�o, roxo, cru",
"Gr�o-de-bico, cru",
"Guandu, cru",
"Lentilha, cozida",
"Lentilha, crua",
"Pa�oca, amendoim",
"P�-de-moleque, amendoim",
"Soja, farinha",
"Soja, extrato sol�vel, natural, fluido",
"Soja, extrato sol�vel, p�",
"Soja, queijo (tofu)",
"Tremo�o, cru",
"Tremo�o, em conserva",
"Am�ndoa, torrada, salgada",
"Castanha-de-caju, torrada, salgada",
"Castanha-do-Brasil, crua",
"Coco, cru",
"Coco, verde, cru",
"Farinha, de mesocarpo de baba�u, crua",
"Gergelim, semente",
"Linha�a, semente",
"Pinh�o, cozido",
"Pupunha, cozida",
"Noz, crua"
  ]);

  export {objeto}